before_script:
  - "sudo pip install pgxnclient"
  - "sudo apt-get install libv8-dev"
  - "sudo pgxn install plv8"
  - "dropdb --if-exists -U postgres test"
  - "createdb -U postgres test"

script:
  - "TESTDBNAME=test npm run test"

notifications:
  irc: "irc.freenode.org#pgrest"

language: node_js

node_js:
  - 0.8
  - 0.9

